remote_theme: H-COOH/theme

title: Mi's Blog
description: 探索世界，发现精彩，记录生活

plugins:
  - jekyll-feed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"